# Generated by Django 5.1.4 on 2024-12-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goleancer', '0002_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='service_offer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
