# Generated by Django 5.1.4 on 2024-12-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goleancer', '0005_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='userchoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
    ]
